### ISSUE TITLE
license???

### ISSUE THREAD

**Issue by ghost** [bol-van/me-disable#2]
hey, buddy. you might want to add a license here, as this code is in a sort of legal limbo here as long as you dont have a license, afiak. (i am no lawyer, this is not legal advice. just a suggestion to put a license here.)

**Comment by ghost** [comment]
i recommend using MIT license, as thats what I use 99% of the time. also, i am using that license until you use a license besides MIT license. however, i am giving credit to you and i equally in said license. please do a pull request on my fork if you decide not to use MIT license.

**Comment by bol-van** [comment]
This program worths nothing. It's like hello world :) No license required, consider its public domain

**Comment by ghost** [comment]
ok then thank you for the generous donation to the community.
